### ISSUE TITLE
prepare open science network demo

### ISSUE THREAD

**Issue by mayel** [bonfire-networks/bonfire-app#1016]
- [x] orcid login & import #896 #859 
- [x] sharing publication links pulls in metadata and shows it next to the post 
- [x] researcher profiles with institutions and tags #1015 
- [x] post labeling #831 
	- [x] when loading a page it only shows one label media link, when 2+ where added (and displayed in feed)
- [x] pinning as 'accepted answer' https://github.com/bonfire-networks/bonfire-app/issues/986
- [x] openalex integration
