### ISSUE TITLE
[meta] Bonfire social user journey

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#102]
- [x] When like a post, the counter does not update
- [ ] When creating or boosting a post, the timeline does not update correctly
- [x] push notifications are not implemented
- [ ] Posts section in user profile shows the whole user timeline
- [ ] Boosts section in user profile shows the whole user timeline
- [ ] a reply activity in timeline should not show the action component below the replied comment
- [ ] activities in timeline should have an icon to highlight the boundary selected
- [ ] CW are not rendered in timelines
- [x] when I create a new post I cannot use markdown
- [x] when I create a new post I cannot mention another user
- [x] when I create a new post I cannot create hashtags (or they are not highlited in a different way)
- [ ] The thread page UX/UI is broken (there are multiple textareas and it's confusing where to reply, ideally there should be only the textarea on the left sidebar and the user should clearly understand if s/he is replying to the main post or to a reply)
- [x] The replies are not rendered correctly
- [x] The tree of comment is not rendered correctly
- [x] The favourited view is not hooked to the correct feed
- [x] Search page is broken
- [ ] Admin | configure instance section is not hooked to the BE
- [ ] Admin | invites section is not hooked to the BE
- [ ] Admin | reports section is not hooked to the BE
- [ ] Settings | the logged user cannot edit the password or email
- [ ] Settings | the logged user cannot delete themself from the instance
- [x] The notification feed includes also logged user replies to its own activities

**Comment by mayel** [comment]
mentions are working, but you need to type the full username (eg `@ivan`) in the post until some autocomplete UI is set up

**Comment by mayel** [comment]
also hashtags are working on my end

**Comment by mayel** [comment]
Remaining `.leex` files (especially ones calling `live_component` to embed a Surface component) need to be ported to Surface so that we can upgrade to 0.6 which supports recursive components, to fix threads

**Comment by mayel** [comment]
CKeditor has now been adding with @ mention auto-completion and markdown formatting.

**Comment by ivanminutillo** [comment]
> CKeditor has now been adding with @ mention auto-completion and markdown formatting.

it's working only the md formatting on my side, there's no dropdown when I type @

**Comment by ivanminutillo** [comment]
> also hashtags are working on my end

How can I test hashtags fro the gui ?

**Comment by ivanminutillo** [comment]
I think we can close this as we created separated issues for each item in the list
