### ISSUE TITLE
[meta] Backend bugswatting roundup (sister of #102)

### ISSUE THREAD

**Issue by jjl** [bonfire-networks/bonfire-app#103]
* [ ] Add ACL name to feed entries (for those permitted to see them, basically authors right now) #114
* [ ] List ACLs API #114
* [ ] Invites APIs (CRUD) #113
* [ ] Flags APIs (CRUD) #112
* [ ] Instance config APIs
* [ ] Data deletion #79 
  * [ ] User 
  * [ ] Account

**Comment by mayel** [comment]
Closed in favour of smaller issues
