### ISSUE TITLE
Add a way to specifically allow-list remote domains/users for federation

### ISSUE THREAD

**Issue by mayel** [bonfire-networks/bonfire-app#1038]
Useful for both allow-list (archipelago mode) and consent-based federation, related to #1037

This could be done with dedicated circles (one for the instance + one for each user) and extra option in relevant dropdowns to add to them. These would probably only be used for allow-listed-only or consent-based federation. 

As a starting point, since we already store a list of known instances and a list of known actors, we could maybe re-use those (at least for instance-wide allowlists), but would also need: 

- [x] page to browse known instance in settings
- [x] ways to block actors/instances already on the list (related to #195 and #199)
- [x] option to delete a known actor
- [x] ideally add special built-in allow-list circles, just like we have blocklists
- [x] a new federation mode setting for allow-list federation (related to #1039)
- [x] checking if allowlist mode is enabled and looking up allow lists before accepting activities from an actor/instance, or before fetching manually
- [x] a way for mods to lookup and add new actors/instances to the list
- [ ] option to remove a remote instance (and delete the copy of all its users and content) (related to #1011)
- [x] view lists of remote actors/instances filtered by blocked or not

**Comment by mayel** [comment]
initial version done :)
