### ISSUE TITLE
Leftover bugs from dogfooding milestone

### ISSUE THREAD

**Issue by ivanminutillo** [bonfire-networks/bonfire-app#157]
- [x] Upload does not work anymore
- [ ] live actions (for some reason unlike/unboost/unfollow all update the state of the button, but not the reverse)
    - [ ] a boost activity does not live update on feed
    - [x] a like activity does not live update on feed
    - [x] a follow activity does not live update on profile (the button does not change status)
- [x] In an activity that represent a reply to a post, it does not appear anymore the author of the original post
- [x] live upload not working anymore
- [x] following / follower counters does not work on profile (they show anon users under the tab, but counters remains at 0 )
- [x] when I visit a user profile, I see my activities in their timeline
- [x] when someone follows me I do not receive any notification (ambigous, I cannot understand when it's working and when not)
    -> hmm, you should, need to check tests
- [x] Replies to my posts dont appear in my notification feed 
    -> hmm, they should, need to check tests
- [x] Autocomplete returns an error when trying to mention a user in the create activity form: 
```
extension.js:76 There has been a problem with the tag search: SyntaxError: Unexpected token < in JSON at position 0
```
- [x] Publishing a reply on the thread page, it does not live update
- [x] switching themes (on bonjour) fails with `unknown hook found for "Themeable"`
- [x] Load more are not appearing anymore in home/local feeds
    -> I see the button but it doesn't actually paginate any more
- [x] Boosted activity does not show anymore the original author 
![](https://i.imgur.com/QQOeqc2.png)
- [x] After I register myself, I do not see anymore the form for creating a new user 
![](https://i.imgur.com/8VkJsUQ.png)
- [x] the follow button shows also on my profile

**Comment by jjl** [comment]
Superseded by #240
