### ISSUE TITLE
[meta] issue drafts

### ISSUE THREAD

**Issue by mayel** [bonfire-networks/bonfire-app#164]
# Alpha issues
**milestone goal**: Focused on user safety, like flag/block/delete, and federating with other ActivityPub apps.

- [x] [Mix task to promote a user to an administrator in development](https://github.com/bonfire-networks/bonfire-app/issues/162)
- [x] [Mix task for creating an activated account in development](https://github.com/bonfire-networks/bonfire-app/issues/161)
- [x] [Simplest DM flow](https://github.com/bonfire-networks/bonfire-app/issues/154)
- [x] [When i visit a thread page, the create activity form should default to reply to the main thread](https://github.com/bonfire-networks/bonfire-app/issues/149)
- [x] [An admin can make other users admin](https://github.com/bonfire-networks/bonfire-app/issues/146)
- [ ] [Leftover bugs from dogfooding milestone](https://github.com/bonfire-networks/bonfire-app/issues/157)
- [ ] [When I click Reply it should automatically add the actor I'm replying to as an @ mention (and probably others involved in the discussion)](https://github.com/bonfire-networks/bonfire-app/issues/156)
- [ ] [Block an entire remote instance (either as a user or istance-wide by admin)](https://github.com/bonfire-networks/bonfire-app/issues/139)
- [ ] [UI to handle flags](https://github.com/bonfire-networks/bonfire-app/issues/140)
- [ ] [Block a local user or remote actor (either as a user or istance-wide by admin)](https://github.com/bonfire-networks/bonfire-app/issues/138)
- [ ] [Deletion of objects/activities by the creator or admin](https://github.com/bonfire-networks/bonfire-app/issues/137)
- [ ] [Test federation across bonfire and other fediverse servers](https://github.com/bonfire-networks/bonfire-app/issues/126)
- [ ] [Implement follow requests and locked accounts](https://github.com/bonfire-networks/bonfire-app/issues/158)
- [ ] [Inviting people to join an instance](https://github.com/bonfire-networks/bonfire-app/issues/113)
- [ ] [breaking down epic acts into smaller more reusable pieces](https://github.com/bonfire-networks/bonfire-app/issues/163)
- [ ] #166
- [ ] #167
- [ ] #165
- [x] [Create a barebones extension as a template that can be used as a base for building new extensions that aren't like existing ones ](https://github.com/bonfire-networks/bonfire-app/issues/134) 

# Issues currently in alpha but to be moved
- [ ] [search activity preview UI](https://github.com/bonfire-networks/bonfire-app/issues/153) - beta
- [ ] [Enable livebook as bonfire extension to start a cookbook](https://github.com/bonfire-networks/bonfire-app/issues/152) - beta
- [ ] [Add proper default images for avatar and background user profile](https://github.com/bonfire-networks/bonfire-app/issues/151) - beta
- [ ] [Improve responsive](https://github.com/bonfire-networks/bonfire-app/issues/145) - beta
- [ ] [Search UI](https://github.com/bonfire-networks/bonfire-app/issues/141) - beta
- [ ] [Edit my account (email)](https://github.com/bonfire-networks/bonfire-app/issues/10) - beta
- [ ] [Create a users directory](https://github.com/bonfire-networks/bonfire-app/issues/159) - beta

# Issues for beta milestone 
**milestone goal**: People and communities should be able to setup and customise their own instance, follow each other, share content, have discussions (private or public), etc, whether they use Bonfire or other fediverse software.

- [ ] [Make sure all string are localisable + translate the UI into at least one language](https://github.com/bonfire-networks/bonfire-app/issues/155) - beta
- [ ] [Add emoji on the create activity form](https://github.com/bonfire-networks/bonfire-app/issues/150) - beta
- [ ] [As a user I want to upload images in my post](https://github.com/bonfire-networks/bonfire-app/issues/148) - beta
- [ ] [As a user I want to know if I have unread/new notifications](https://github.com/bonfire-networks/bonfire-app/issues/147) - beta -> please expand, does this mean keeping track of read status, does it mean the notification button in navbar changes?
- [ ] #173
- [ ] [popular hashtags widget](https://github.com/bonfire-networks/bonfire-app/issues/144) - beta
- [ ] [Delete my account or user + data](https://github.com/bonfire-networks/bonfire-app/issues/79) - beta
- [ ] #174
- [ ] #175
- [ ] #176
- [ ] #177
- [ ] #178
- [ ] #179
- [ ] #180
- [ ] #181
- [ ] #182
- [ ] #183
- [ ] #184

## To move from backlog
- [ ] [Improve Direct Messages UX](https://github.com/bonfire-networks/bonfire-app/issues/160) - beta
- [ ] [Create an empty flavour that can be used as a base for building new applications that aren't like existing ones](https://github.com/bonfire-networks/bonfire-app/issues/106) - beta or backlog
- [ ] [Per-user configuration for federation handling (i.e. preferred apps/extensions)](https://github.com/bonfire-networks/bonfire-app/issues/40) - beta?
- [ ] [UI for federation configuration ](https://github.com/bonfire-networks/bonfire-app/issues/39) - beta?

# Backlog / no milestone / TBD
- [ ] #168
- [ ] [Backlinks in discussions](https://github.com/bonfire-networks/bonfire-app/issues/142) 
- [ ] [Change username](https://github.com/bonfire-networks/bonfire-app/issues/9) (with old username remaining as an alias and canonical URL, basically this just adds an alias username for webfinger) - backlog
- [ ] [Customise bonfire without forking](https://github.com/bonfire-networks/bonfire-app/issues/89) - backlog
- [ ] [Config-driven routing](https://github.com/bonfire-networks/bonfire-app/issues/88) - backlog
- [ ] [Download my user data ](https://github.com/bonfire-networks/bonfire-app/issues/80) - backlog
- [ ] [Localisation of tags ](https://github.com/bonfire-networks/bonfire-app/issues/31)  - backlog
- [ ] [Fork a tag, incl. on another instance](https://github.com/bonfire-networks/bonfire-app/issues/47)  - backlog
- [ ] #169
- [ ] #170
- [ ] #171
- [ ] #172
