### ISSUE TITLE
Backlog issue list

### ISSUE THREAD

**Issue by mayel** [bonfire-networks/bonfire-app#475]
### Should
- [ ] Add members modal UX ![](https://i.imgur.com/bECf4uY.png)
- [x] my own activities shouldn’t be counted when counting Seen for notifications bar, or for showing unread messages in threads list [#374](https://github.com/bonfire-networks/bonfire-app/issues/374)
- [x] Bug: if I disabled showing notifications or follows in feed, I should *not* receive a live update for them in home feed #381 
- [ ] The X on the “thanks for registering popup” is barely/non functional on iOS Safari.
- [ ] Uploading profile picture needed a reloading of the page to show the new image
- [x] users suggestions should include all discoverable local users, ohter than followed / followers 

### Would
- [ ] Minor UI issue: the "Follow" button on a topic page is right up against the bottom of the top box containing the topic title and description. Also a minor design inconsistency where most of the buttons I see are rounded rectangles, but the "Follow" button inside of a topic itself has fully rounded/semicircular ends.

### Should (for v1.0)
- [ ] Re-organise / simplify migrations in flavours & Auto-add migrations when installing/upgrading an extension #243 (see `Mix.Tasks.Rauversion.CopyMigrations`)
- [ ] Unflag action should not require reload to see effect
- [ ] Add a view to block instances -> ?
- [ ] Improvement: add visual indicators / feedbacks when the platform is loading contents / performing operations #386 
- [x] View all users (local and/or remote) from a single view and block them (or deactivate entirely?)
- [ ] List functions which are intended to be public APIs in extenions (maybe using an inline tag) and use something like https://github.com/DCzajkowski/snapshy to check for changes between releases
- [ ] #874
- [x] #875
- [ ] #876
- [x] fix Presence so clicking reply on one tab doesn't open the composer on the other if two tabs are open in same browser -> now opens in two tabs, need to find a better way
- [ ] optimise OTP release, seems assets are in triplicate:
	./bonfire/lib/bonfire_umbrella-0.4.0-classic-beta.9/priv
	./bonfire/lib/bonfire-0.1.0-beta.3/priv
	./bonfire/lib/bonfire_ui_common-0.1.0/priv
- [x] #1080
    
### Would (for v1.0)
- [ ] Implement sub-types so we can handle (eg. generate paths or show previews) different kinds of the same Pointer (eg Intent can be Need, Offer, Task, etc)
- [ ] Feature Proposal: Let people choose what types of posts show in their default (or local) timeline, also more tabs #460 
- [x] #877
- [ ] Add a view to create the instance topics
- [ ] A way to message all local admins (or people with a specific role) #169 
- [ ] #879
- [ ] #878
- [ ] Implement password-less auth https://github.com/liveshowy/webauthn_live_component/

### Should
- [ ] As a mod I want to have a log of all flagged activities / users (incl. resolved ones) #354 
- [x] Show a label on the user profile if you ghosted/silenced that user 
- [ ] clicking on the date of a comment in thread should just scroll rather than reload [#376](https://github.com/bonfire-networks/bonfire-app/issues/376)
- [ ] Add counters to likes / boosts / replies actions #272
- [x] Optional display of new activities (eg. a post someone you follow published while you were looking at your feed) in feeds #204 
- [ ] Notification: Might be good to have multiple tabs for different types of notifications (likes, boosts, mentions, different extensions?) 
- [x] Edit the thread title do not work anymore (A case condition didn't receive data in a format it could recognise)
- [ ] Review minimal subject text inconsistencies (ivan assigned to ivan / ivan labelled / ...)
- [x] Boosting an activity in the thread view does not automatically update the icon status beta-testing #258
- [x] Push deletions to feeds (so existing activities/posts on currently loaded feeds dissappear) [#442](https://github.com/bonfire-networks/bonfire-app/issues/442) 
- [ ] filter local/remote feeds by discussion/etc
- [ ] #881
- [ ] #882

### Would
- [ ] Add the editor inline in threads
- [ ] Configuration: Switch between quoted activity and a "show thread button" in timelines [#387](https://github.com/bonfire-networks/bonfire-app/issues/387)
- [ ] Pin to topic
- [ ] User should be able to pin activities to the top of their outbox feed #[216](https://github.com/bonfire-networks/bonfire-app/issues/216) 
- [ ] Improve uploaded media a11y [#408](https://github.com/bonfire-networks/bonfire-app/issues/408)
- [x] Allow users to 'delete and redraft' (or edit??) posts #390 
- [x] Implement optional flat discussion UX #168
- [ ] UI: Improve the task preview when repliyng a task in feeds
![](https://i.imgur.com/n2yWJDL.png)

### Should
- Edit my account (email address) [#10](https://github.com/bonfire-networks/bonfire-app/issues/10) -> initial implementation done, but we should verify the new address before updating...
- (Add screen to enable/disable 2FA in settings) I didn't want to activate 2FA/TOTP when signing up but now I cannot find where to do it on the settings [#360]
- Download my user data #80 
- Delete my account or user + data [#79](https://github.com/bonfire-networksbonfire-app/issues/79)

### Would
- Import my data (from another Bonfire instance or from Mastodon) #245 
- Migrate my account (between Bonfire or Mastodon instances) #246 
(https://github.com/bonfire-networks/bonfire-app/issues/360)
- New UX to create a team/organisation

### Should
- [ ] add a verb/permission for that (who can see your online status) 
- [x] show which actions you're allowed to do (changing icon based on permissions) in activity preview
- [ ] #883
- [ ] Save composer added circles/users <> roles as a new boundary
- [ ] Create a map role-related verbs associated with settings keys so that we can show the right settings (and check permissions on settings mutations)
- [x] follow and dm buttons on hero profile should be hidden if the user is ghosted/silenced accordingly -> if you're ghosted you shouldn't be able to see the profile at all, and if you're silenced maybe we shouldn't make that obvious
- [ ] apply boundaries to Requests and then be able to view someone's requests/requested that involve me
- [ ] maybe remove the logic which auto-grants permissions to reply_to and mentions (and rely on the composer instead, for more explicitness)

### Would

# Feedback

- Tried to make a circle for just myself, and had a hard time figuring out how to do that. Wasn't sure what the difference between boundaries and circles is, and was a little confused when I could make a boundary while posting, but not a circle. When I made a boundary from the posting window, I wasn't able to add individual users. I made a circle from the Boundaries and Circles tab, and was able to add myself to the same circle twice, once by username and once from the "Suggested Users" tab, and then could not delete either one from the circle (error: "Could not remove from circle"). Further, when I added myself by username, an "undefined" field remained in the box where I input my username. 

- Boundaries and search indexing settings #244 
- Create roles
    - Instance default roles
        - Guest
        - Remote User
        - Local User
        - Observer (can view flags, blocks, ghosts, silence, hiden posts)
        - Moderator (can block, ghost, silence, hide posts, remove flags)
        - Caretaker (Can edit instance settings, delete posts, invite users, and also moderate)
        - Admin (anything)
    - Social default roles
        - Blocked (Can NOT view or interact with the content)
        - Viewer (Can only view the content)
        - Follower (Can view and react)
        - Participant (Can view, react, and reply)
        - Caretaker (Can view/react/reply, [edit] and delete)
    - Topics default roles
        - Follower (can read/follow the topic, and suggest new posts)
        - Poster (can publish directly)
        - Reviewer (can publish suggestions)
        - Caretaker (can tag new activities, create subtopics, edit topic settings)
    - Coordination default roles
        - Facilitator (can assign tasks, edit due date, close tasks)
        - 
    - User default roles
- Silence an entire remote instance (instance-wide by admin) #139
- Silence an entire remote instance (as a user) #195 
- See if we can block an object (instead of only actors) to hide it from feeds (either as a user, or as an admin instance-wide)
