### ISSUE TITLE
Run automated ActivityPub test suites

### ISSUE THREAD

**Issue by mayel** [bonfire-networks/bonfire-app#868]
##  Bonfire automated test suites

- [x] unit tests
- [x] automated integration tests (dance mode, with 2 bonfire instances)
- [x] automated live federation tests

### Previous status (Jan 25)

- activity_pub: 293 tests, 61 failures, 29 excluded
- integration: 63 tests, 2 failures (pixelfed + emoji reaction)

### Latest status (April 25)

- [x] activity_pub: 301 tests, 62 failures, 27 excluded
  - [x] forks/activity_pub/test/activity_pub/federator/activity_pub_controller_test.exs:93
  - [x] like forks/activity_pub/test/activity_pub/data/activity_pub_test.exs:163
  - [x] ttest /objects/:uuid does not return local-only objects for remote users - `forks/activity_pub/test/activity_pub/federator/activity_pub_controller_test.exs:126` @ Elixir.ActivityPub.Web.ActivityPubControllerTest
  - [x] test /objects/:uuid it returns 401 for non-public posts - `forks/activity_pub/test/activity_pub/federator/activity_pub_controller_test.exs:218` @ Elixir.ActivityPub.Web.ActivityPubControllerTest
  - [x] test /shared_inbox it clears `unreachable` federation status of the sender - `forks/activity_pub/test/activity_pub/federator/activity_pub_controller_test.exs:496` @ Elixir.ActivityPub.Web.ActivityPubControllerTest
  - [x] test /shared_inbox it inserts an incoming activity into the database - `forks/activity_pub/test/activity_pub/federator/activity_pub_controller_test.exs:446` @ Elixir.ActivityPub.Web.ActivityPubControllerTest
  - [x] test /shared_inbox it inserts an incoming activity into the databaseeven if we can't fetch the user but have it in our db - `forks/activity_pub/test/activity_pub/federator/activity_pub_controller_test.exs:466` @ Elixir.ActivityPub.Web.ActivityPubControllerTest
  - [x] test /users/:nickname/followers it returns the followers in a collection - `forks/activity_pub/test/activity_pub/federator/activity_pub_controller_test.exs:772` @ Elixir.ActivityPub.Web.ActivityPubControllerTest
  - [x] test /users/:nickname/followers it works for more than 10 users - `forks/activity_pub/test/activity_pub/federator/activity_pub_controller_test.exs:833` @ Elixir.ActivityPub.Web.ActivityPubControllerTest
  - [x] test /users/:nickname/following it returns the following in a collection - `forks/activity_pub/test/activity_pub/federator/activity_pub_controller_test.exs:871` @ Elixir.ActivityPub.Web.ActivityPubControllerTest
  - [x] test /users/:nickname/following it works for more than 10 users - `forks/activity_pub/test/activity_pub/federator/activity_pub_controller_test.exs:932` @ Elixir.ActivityPub.Web.ActivityPubControllerTest
  - [x] test /users/:nickname/inbox it accepts messages with bcc as string instead of array - `forks/activity_pub/test/activity_pub/federator/activity_pub_controller_test.exs:591` @ Elixir.ActivityPub.Web.ActivityPubControllerTest
  - [x] test /users/:nickname/inbox it accepts messages with cc as string instead of array - `forks/activity_pub/test/activity_pub/federator/activity_pub_controller_test.exs:568` @ Elixir.ActivityPub.Web.ActivityPubControllerTest
  - [x] test /users/:nickname/inbox it accepts messages with to as string instead of array - `forks/activity_pub/test/activity_pub/federator/activity_pub_controller_test.exs:546` @ Elixir.ActivityPub.Web.ActivityPubControllerTest
  - [x] test /users/:nickname/inbox it inserts an incoming activity into the database - `forks/activity_pub/test/activity_pub/federator/activity_pub_controller_test.exs:526` @ Elixir.ActivityPub.Web.ActivityPubControllerTest
  - [x] test GET /users/:nickname/outbox it returns 200 even if there're no activities - `forks/activity_pub/test/activity_pub/federator/activity_pub_controller_test.exs:663` @ Elixir.ActivityPub.Web.ActivityPubControllerTest
  - [x] test activities at /objects/:uuid it doesn't return a local-only activity - `forks/activity_pub/test/activity_pub/federator/activity_pub_controller_test.exs:311` @ Elixir.ActivityPub.Web.ActivityPubControllerTest
  - [x] test activities at /objects/:uuid it returns 404 for non-public activities - `forks/activity_pub/test/activity_pub/federator/activity_pub_controller_test.exs:353` @ Elixir.ActivityPub.Web.ActivityPubControllerTest
  - [x] it clears `unreachable` federation status of the sender `forks/activity_pub/test/activity_pub/federator/activity_pub_controller_test.exs:523`
  - [x] forks/activity_pub/test/activity_pub/federator/fetcher_test.exs:78
  - [x] forks/activity_pub/test/activity_pub/federator/fetcher_test.exs:94 why is fetch_object_from_id returning an Object instead of an Actor
  - [x] forks/activity_pub/test/activity_pub/federator/fetcher_test.exs:252
  - [x] forks/activity_pub/test/activity_pub/federator/fetcher_test.exs:275
  - [x] forks/activity_pub/test/activity_pub/federator/fetcher_test.exs:298
  - [x] forks/activity_pub/test/activity_pub/federator/fetcher_test.exs:646
  - [x] forks/activity_pub/test/activity_pub/federator/fetcher_test.exs:665
  - [x] forks/activity_pub/test/activity_pub/federator/webfinger_test.exs:17
  - [x] forks/activity_pub/test/activity_pub/federator/webfinger_test.exs:28
  - [x] forks/activity_pub/test/activity_pub/federator/webfinger_test.exs:46
  - [x] forks/activity_pub/test/activity_pub/federator/webfinger_test.exs:54
  - [x] MFM forks/activity_pub/test/activity_pub/data/transformer/note_handling_test.exs:478
  - [x] forks/activity_pub/test/activity_pub/data/transformer/user_update_handling_test.exs:57
  - [x] forks/activity_pub/test/activity_pub/data/transformer/follow_handling_test.exs:130
  - [x] forks/activity_pub/test/activity_pub/data/transformer/accept_handling_test.exs:71
  - [x] boost forks/activity_pub/test/activity_pub/data/activity_pub_test.exs:211
  - [x] undo boost forks/activity_pub/test/activity_pub/data/activity_pub_test.exs:230
  - [x] forks/activity_pub/test/activity_pub/data/transformer/announce_handling_test.exs:94
  - [x] forks/activity_pub/test/activity_pub/data/transformer/announce_handling_test.exs:71
  - [x] forks/activity_pub/test/activity_pub/data/transformer/announce_handling_test.exs:44
  - [x] forks/activity_pub/test/activity_pub/data/transformer/replies_handling_test.exs:174
  - [x] forks/activity_pub/test/activity_pub/data/transformer/replies_handling_test.exs:335
  - [x] forks/activity_pub/test/activity_pub/data/transformer/replies_handling_test.exs:200
  - [x] forks/activity_pub/test/activity_pub/data/transformer/replies_handling_test.exs:158
  - [x] forks/activity_pub/test/activity_pub/data/transformer/flag_handling_test.exs:19
  - [x] forks/activity_pub/test/activity_pub/data/activity_pub_test.exs:118
  - [ ] https://github.com/bonfire-networks/bonfire-app/issues/837 and https://github.com/bonfire-networks/bonfire-app/issues/780
	  - [x] forks/activity_pub/test/activity_pub/data/transformer/delete_handling_test.exs:23
	  - [x] forks/activity_pub/test/activity_pub/data/transformer/delete_handling_test.exs:50
	  - [x] forks/activity_pub/test/activity_pub/data/transformer/delete_handling_test.exs:91
	  - [x] forks/activity_pub/test/activity_pub/data/transformer/delete_handling_test.exs:109
	  - [x] forks/activity_pub/test/activity_pub/data/transformer/delete_handling_test.exs:157
	  - [ ] test /objects/:uuid it returns 404 for tombstone objects - `forks/activity_pub/test/activity_pub/federator/activity_pub_controller_test.exs:253` @ Elixir.ActivityPub.Web.ActivityPubControllerTest
  - [x] forks/activity_pub/test/activity_pub/data/transformer/article_handling_test.exs:47
  - [x] forks/activity_pub/test/activity_pub/federator/move_test.exs:216
  - [x] forks/activity_pub/test/activity_pub/federator/move_test.exs:87
  - [x] forks/activity_pub/test/activity_pub/federator/move_test.exs:198
  - [x] forks/activity_pub/test/activity_pub/federator/move_test.exs:47
  - [x] forks/activity_pub/test/activity_pub/data/encryption_test.exs:58
  - [x] forks/activity_pub/test/activity_pub/data/encryption_test.exs:65
  - [x] test /shared_inbox it clears `unreachable` federation status of the sender forks/activity_pub/test/activity_pub/federator/activity_pub_controller_test.exs:532
	- [x] test /objects/:uuid it doesn't return a local-only object    forks/activity_pub/test/activity_pub/federator/activity_pub_controller_test.exs:93
	- [x] test GET /users/:nickname/outbox it does not return a local note activity when unauthenticated    forks/activity_pub/test/activity_pub/federator/activity_pub_controller_test.exs:744
	- [x] test activities at /objects/:uuid it doesn't return a local-only activity      forks/activity_pub/test/activity_pub/federator/activity_pub_controller_test.exs:321
	- [x] test /objects/:uuid does not return local-only objects for remote users    forks/activity_pub/test/activity_pub/federator/activity_pub_controller_test.exs:126
	- [x] test implementation quirks it can fetch peertube videos, incl. a Group actor     forks/activity_pub/test/activity_pub/federator/fetcher_test.exs:314
	

- [x] integration 63 tests, 15 failures
  - [x] publication date extensions/bonfire_federate_activitypub/test/activity_pub_integration/post_data_test.exs:263
  - [x] emoji reaction extensions/bonfire_federate_activitypub/test/activity_pub_integration/activity_fallback_test.exs:43
  - [x] peertube extensions/bonfire_federate_activitypub/test/activity_pub_integration/activity_fallback_test.exs:26
  - [x] pixelfed extensions/bonfire_federate_activitypub/test/activity_pub_integration/post_web_test.exs:89
  - [x] extensions/bonfire_federate_activitypub/test/activity_pub_integration/message_integration_test.exs:78
  - [x] extensions/bonfire_federate_activitypub/test/activity_pub_integration/post_data_test.exs:225
- [x] boundaries 107 tests, 10 failures
- [x] dance (with 2 instances) 38 tests, 20 failures, 1 invalid
  - [x] move instance https://github.com/bonfire-networks/bonfire-app/issues/1193 : extensions/bonfire_federate_activitypub/test/dance/move_dance_test.exs:17
  - [x] delete user https://github.com/bonfire-networks/bonfire-app/issues/780 : extensions/bonfire_federate_activitypub/test/dance/delete_user_dance_test.exs:21
  - [x] https://github.com/bonfire-networks/bonfire-app/issues/565 extensions/bonfire_federate_activitypub/test/dance/moderation_dance_test.exs:17
   - [x] extensions/bonfire_federate_activitypub/test/dance/mentions_replies_public_dance_test.exs:21
  - [x] extensions/bonfire_federate_activitypub/test/dance/mentions_replies_private_dance_test.exs:22
  - [x] extensions/bonfire_federate_activitypub/test/dance/remote_boundaries_dance_test.exs:102
  - [x] extensions/bonfire_federate_activitypub/test/dance/remote_boundaries_dance_test.exs:236
- [ ] #1198
- [ ] #1199
- [ ] #871 
- [ ] #872 

## Out of scope for now

  - [ ] extensions/bonfire_classify/test/dance/group_dance_test.exs:20
  - [ ] extensions/bonfire_classify/test/dance/post_in_group_dance_test.exs:22

## Some other possible automated test suites

- [ ] #822 and https://verify.funfedi.dev/ (integration in progress)
- [x] https://socialweb.coop/activitypub-testing/announcement/ (fixed outbox must use `OrderedCollection` and made note of #871 #872) 
- [ ] https://codeberg.org/helge/fediverse-features (WIP: https://codeberg.org/bonfire/fediverse-features/src/branch/elixir-bonfire-tests)

---

- [ ] https://feditest.org/ & https://github.com/fediverse-devnet/testsuite (not yet available)
- [ ] https://github.com/Letterbook/Sandcastles (a way to run several fedi apps side-by-side, but not in itself a test suite)
- [ ] https://aptestsuite.stevebate.dev/ (seems like a checklist, not a test suite)
- [ ] https://tinysubversions.com/notes/activitypub-tool/ (basic inbox test, seems to no longer work)
- [ ] https://github.com/go-fed/testsuite (offline & not maintained)
- [ ] https://test.activitypub.dev (offline)
- [ ] https://pubkit.net/ / https://mastodon.social/@dansup/112003314063840346  (not available)
- [ ] and others being discussed at https://venera.social/profile/activitypubtestsuite
